<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InputTagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tb_input_tag')->insert([
            ['tag_no' => '1JI-MP007', 'address_no' => '1JI-MP007', 'description' => 'GGO', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 1, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1JX-AP021', 'address_no' => '1JX-AP021', 'description' => 'Total Unit Aux Load', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 2, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TY-BA639', 'address_no' => '1TY-BA639', 'description' => 'ID FAN A OUTLET TEMP', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 3, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TY-BA634', 'address_no' => '1TY-BA634', 'description' => 'ID FAN B OUTLET TEMP', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 4, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1AR-BA018', 'address_no' => '1AR-BA018', 'description' => 'AVG ECON GAS OUTLET OXYGEN',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 5, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TI-MS507', 'address_no' => '1TI-MS507', 'description' => 'MAIN STEAM TEMP', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 6, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TI-HR505', 'address_no' => '1TI-HR505', 'description' => 'HOT REHEAT STEAM', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 7, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PI-MS004', 'address_no' => '1PI-MS004', 'description' => 'MAIN STEAM PRESS (AVG)', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 8, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-FW511', 'address_no' => '1FI-FW511', 'description' => 'SUPERHEATER SPRAY FLOW', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 9, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-FW516', 'address_no' => '1FI-FW516', 'description' => 'REHEATER SPRAY FLOW', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 10, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-CD005', 'address_no' => '1PT-CD005', 'description' => 'CDSR VACUUM', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 11, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1JX-AP021', 'address_no' => '1JX-AP021', 'description' => 'TOTAL UNIT AUX LOAD', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 12, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-FW503', 'address_no' => '1TE-FW503', 'description' => 'ECONOMISER INLET TEMP', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 13, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TY-BA601', 'address_no' => '1TY-BA601', 'description' => 'SAH A AIR INLET TEMP',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 14, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TY-BA627', 'address_no' => '1TY-BA627', 'description' => 'SAH A GAS INLET TEMP',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 15, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TY-BA629', 'address_no' => '1TY-BA629', 'description' => 'SAH A GAS OUTLET TEMP',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 16, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TY-BA600', 'address_no' => '1TY-BA600', 'description' => 'SAH B AIR INLET TEMP',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 17, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TY-BA622', 'address_no' => '1TY-BA622', 'description' => 'SAH B GAS INLET TEMP',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 18, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TY-BA624', 'address_no' => '1TY-BA624', 'description' => 'SAH B GAS OUTLET TEMP',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 19, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BA647', 'address_no' => '1TE-BA647', 'description' => 'FD FAN A OUTLET TEMP', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 20, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BA648', 'address_no' => '1TE-BA648', 'description' => 'FD FAN B OUTLET TEMP', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 21, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-MS509', 'address_no' => '1FI-MS509', 'description' => 'MAIN STEAM FLOW', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 22, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1JI-MP007', 'address_no' => '1JI-MP007', 'description' => 'GGO', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 23, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-BY517A','address_no' => '1FI-BY517A',  'description' => 'Coal Flow Mill A', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 24, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-BY517B','address_no' => '1FI-BY517B',  'description' => 'Coal Flow Mill B', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 25, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-BY517C','address_no' => '1FI-BY517C',  'description' => 'Coal Flow Mill C', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 26, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-BY517D','address_no' => '1FI-BY517D',  'description' => 'Coal Flow Mill D', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 27, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-BY517E','address_no' => '1FI-BY517E',  'description' => 'Coal Flow Mill E', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 28, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TI-BA085', 'address_no' => '1TI-BA085', 'description' => 'MOT Mill A', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 29, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TI-BA090', 'address_no' => '1TI-BA090', 'description' => 'MOT Mill B', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 30, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TI-BA095', 'address_no' => '1TI-BA095', 'description' => 'MOT Mill C', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 31, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TI-BA100', 'address_no' => '1TI-BA100', 'description' => 'MOT Mill D', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 32, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TI-BA105', 'address_no' => '1TI-BA105', 'description' => 'MOT Mill E', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 33, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-BA110', 'address_no' => '1FI-BA110', 'description' => 'PA Flow', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 34, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-BA109', 'address_no' => '1FI-BA109', 'description' => 'SA Flow', 'group_id' => 5, 'unit_id' => 2, 'urutan' => 35, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1AR-BA018', 'address_no' => '1AR-BA018', 'description' => 'O2 Out A',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 36, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1AR-BA019', 'address_no' => '1AR-BA019', 'description' => 'O2 Out B',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 37, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TY-BA627', 'address_no' => '1TY-BA627', 'description' => 'Eco Out T A',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 38, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TY-BA622', 'address_no' => '1TY-BA622', 'description' => 'Eco Out T B',  'group_id' => 5, 'unit_id' => 2, 'urutan' => 39, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-FW501', 'address_no' => '1FI-FW501', 'description' => 'FEEDWATER FLOW TO ECONOMISER',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 1, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-FW511', 'address_no' => '1FI-FW511', 'description' => 'SUPERHEAT SPRAY FLOW',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 2, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FI-FW516', 'address_no' => '1FI-FW516', 'description' => 'REHEAT SPRAY FLOW',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 3, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1FX-CD013', 'address_no' => '1FX-CD013', 'description' => 'EMERG COND MAKEUP FLOW TO CDSR',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 4, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-MS510', 'address_no' => '1TE-MS510', 'description' => 'HP TURBINE INLET TEMP A',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 5, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-MS511', 'address_no' => '1TE-MS511', 'description' => 'HP TURBINE INLET TEMP B',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 6, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-CR517', 'address_no' => '1TE-CR517', 'description' => 'COLD REHEAT TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 7, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-HR508', 'address_no' => '1TE-HR508', 'description' => 'IP TURB LINE B TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 8, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-HR507', 'address_no' => '1TE-HR507', 'description' => 'HOT REHEAT STEAM OUTLET B TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 9, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-ES354', 'address_no' => '1TE-ES354', 'description' => 'HP HTR #7 STEAM TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 10, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-HD351', 'address_no' => '1TE-HD351', 'description' => 'HP HTR #7 DRAIN TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 11, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-FW369', 'address_no' => '1TE-FW369', 'description' => 'HP HTR #7 OUTLET TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 12, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-FW368', 'address_no' => '1TE-FW368', 'description' => 'HP HTR #6 OUTLET TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 13, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-FW367', 'address_no' => '1TE-FW367', 'description' => 'HP HTR #5 OUTLET TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 14, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-FW366', 'address_no' => '1TE-FW366', 'description' => 'HP HTR #5 INLET TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 15, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PI-FW007', 'address_no' => '1PI-FW007', 'description' => 'DRUM PRESSURE',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 16, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-CD377', 'address_no' => '1TE-CD377', 'description' => 'DEAERATOR TEMPERATURE',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 17, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PI-MS004', 'address_no' => '1PI-MS004', 'description' => 'MAIN STEAM PRESSURE',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 18, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-CR002', 'address_no' => '1PT-CR002', 'description' => 'COLD REHEAT STEAM PRESS',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 19, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-HR010', 'address_no' => '1PT-HR010', 'description' => 'IP TURB LINE B PRESS',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 20, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-HR007', 'address_no' => '1PT-HR007', 'description' => 'IP TURB LINE A PRESS',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 21, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-ES353', 'address_no' => '1PT-ES353', 'description' => 'HP HTR #7 INLET STM PRESS',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 22, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-FW001', 'address_no' => '1PT-FW001', 'description' => 'ECONOMISER INLET PRESS',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 23, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-FW064', 'address_no' => '1PT-FW064', 'description' => 'FEED PUMPS OUTLET HEADER PRESS',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 24, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-CD003', 'address_no' => '1PT-CD003', 'description' => 'CDSR VACUUM (N/RANGE - FOR DEHC)',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 25, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BA583', 'address_no' => '1TE-BA583', 'description' => 'PULV A INLET TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 26, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BA500', 'address_no' => '1TE-BA500', 'description' => 'PULV B INLET TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 27, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BA499', 'address_no' => '1TE-BA499', 'description' => 'PULV C INLET TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 28, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BA498', 'address_no' => '1TE-BA498', 'description' => 'PULV D INLET TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 29, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BA497', 'address_no' => '1TE-BA497', 'description' => 'PULV E INLET TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 30, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BY600A','address_no' => '1TE-BY600A',  'description' => 'PULV A OUTLET TEMP #1',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 31, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BY600B','address_no' => '1TE-BY600B',  'description' => 'PULV A OUTLET TEMP #2',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 32, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BY601A','address_no' => '1TE-BY601A',  'description' => 'PULV B OUTLET TEMP #1',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 33, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BY601B','address_no' => '1TE-BY601B',  'description' => 'PULV B OUTLET TEMP #2',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 34, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BY602A','address_no' => '1TE-BY602A',  'description' => 'PULV C OUTLET TEMP #1',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 35, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BY602B','address_no' => '1TE-BY602B',  'description' => 'PULV C OUTLET TEMP #2',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 36, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BY603A','address_no' => '1TE-BY603A',  'description' => 'PULV D OUTLET TEMP #1',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 37, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BY603B','address_no' => '1TE-BY603B',  'description' => 'PULV D OUTLET TEMP #2',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 38, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BY604A','address_no' => '1TE-BY604A',  'description' => 'PULV E OUTLET TEMP #1',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 39, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-BY604B','address_no' => '1TE-BY604B',  'description' => 'PULV E OUTLET TEMP #2',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 40, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-ES363', 'address_no' => '1TE-ES363', 'description' => 'HP HTR #6 INLET STM TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 41, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-HD352', 'address_no' => '1TE-HD352', 'description' => 'HP HTR #6 DRAIN TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 42, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-ES362', 'address_no' => '1PT-ES362', 'description' => 'HP HTR #6 INLET STM PRESS',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 43, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-ES375', 'address_no' => '1TE-ES375', 'description' => 'HP HTR #5 INLET STM TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 44, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-HD353', 'address_no' => '1TE-HD353', 'description' => 'HP HTR #5 DRAIN TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 45, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-ES374', 'address_no' => '1PT-ES374', 'description' => 'HP HTR #5 INLET STM PRESS',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 46, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-CW353', 'address_no' => '1TE-CW353', 'description' => 'CDSR CW INLET A TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 47, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-CW355', 'address_no' => '1TE-CW355', 'description' => 'CDSR CW OUTLET A TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 48, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-CW361', 'address_no' => '1TE-CW361', 'description' => 'CDSR CW INLET B TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 49, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1TE-CW363', 'address_no' => '1TE-CW363', 'description' => 'CDSR CW OUTLET B TEMP',  'group_id' => 1, 'unit_id' => 2, 'urutan' => 50, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-CD004', 'address_no' => '1PT-CD004', 'description' => 'CDSR VACUUM - NARROW RANGE',  'group_id' => 2, 'unit_id' => 2, 'urutan' => 1, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1PT-CD005', 'address_no' => '1PT-CD005', 'description' => 'CDSR VACUUM - WIDE RANGE',  'group_id' => 2, 'unit_id' => 2, 'urutan' => 2, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1LT-CD082', 'address_no' => '1LT-CD082', 'description' => 'DEAERATOR STORAGE TANK LEVEL',  'group_id' => 2, 'unit_id' => 2, 'urutan' => 3, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            ['tag_no' => '1LT-CD012', 'address_no' => '1LT-CD012', 'description' => 'CONDENSER LEVEL',  'group_id' => 2, 'unit_id' => 2, 'urutan' => 4, 'm_input' => Null, 'jm_input' => 0, 'keterangan' => null, 'status' => 1],
            // ... (lanjutkan untuk sisa data)
        ]);
    }
}
