<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tb_unit')->insert([
            ['unit_id' => 1, 'unit_name' => 'PLTU Paiton 2', 'status' => 1, 'plant_id' => 2, 'tab_manual_aktif' => 3],
            ['unit_id' => 2, 'unit_name' => 'PLTU Paiton 1', 'status' => 1, 'plant_id' => 2, 'tab_manual_aktif' => 6],
            ['unit_id' => 3, 'unit_name' => 'PLTG Gresik G1', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 4, 'unit_name' => 'PLTG Gresik G2', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 5, 'unit_name' => 'PLTU Gresik U1', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 6, 'unit_name' => 'PLTU Gresik U2', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 7, 'unit_name' => 'PLTU Gresik U3', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 8, 'unit_name' => 'PLTU Gresik U4', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 9, 'unit_name' => 'PLTGU Gresik GT 1.1', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 10, 'unit_name' => 'PLTGU Gresik GT 1.2', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 11, 'unit_name' => 'PLTGU Gresik GT 1.3', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 12, 'unit_name' => 'PLTGU Gresik ST 1.0', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 13, 'unit_name' => 'PLTGU Gresik GT 2.1', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 14, 'unit_name' => 'PLTGU Gresik GT 2.2', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 15, 'unit_name' => 'PLTGU Gresik GT 2.3', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 16, 'unit_name' => 'PLTGU Gresik ST 2.0', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 17, 'unit_name' => 'PLTGU Gresik GT 3.1', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 18, 'unit_name' => 'PLTGU Gresik GT 3.2', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 19, 'unit_name' => 'PLTGU Gresik GT 3.3', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 20, 'unit_name' => 'PLTGU Gresik ST 3.0', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 21, 'unit_name' => 'PLTMG Bawean 1', 'status' => 0, 'plant_id' => 14, 'tab_manual_aktif' => 3],
            ['unit_id' => 22, 'unit_name' => 'PLTMG Bawean 2', 'status' => 0, 'plant_id' => 14, 'tab_manual_aktif' => 3],
            ['unit_id' => 23, 'unit_name' => 'PLTMG Bawean 3', 'status' => 0, 'plant_id' => 14, 'tab_manual_aktif' => 3],
            ['unit_id' => 24, 'unit_name' => 'PLTA Ampel Gading 1', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 25, 'unit_name' => 'PLTA Ampel Gading 2', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 26, 'unit_name' => 'PLTA Giringan 1', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 27, 'unit_name' => 'PLTA Giringan 2', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 28, 'unit_name' => 'PLTA Giringan 3', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 29, 'unit_name' => 'PLTA Golang 1', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 30, 'unit_name' => 'PLTA Golang 2', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 31, 'unit_name' => 'PLTA Golang 3', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 32, 'unit_name' => 'PLTA Lodoyo', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 33, 'unit_name' => 'PLTA Mendalan 1', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 34, 'unit_name' => 'PLTA Mendalan 2', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 35, 'unit_name' => 'PLTA Mendalan 3', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 36, 'unit_name' => 'PLTA Mendalan 4', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 37, 'unit_name' => 'PLTA Ngebel', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 38, 'unit_name' => 'PLTA Selorejo', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 39, 'unit_name' => 'PLTA Sengguruh 1', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 40, 'unit_name' => 'PLTA Sengguruh 2', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 41, 'unit_name' => 'PLTA Siman 1', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 42, 'unit_name' => 'PLTA Siman 2', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 43, 'unit_name' => 'PLTA Siman 3', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 44, 'unit_name' => 'PLTA Sutami 1', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 45, 'unit_name' => 'PLTA Sutami 2', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 46, 'unit_name' => 'PLTA Sutami 3', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 47, 'unit_name' => 'PLTA T.Agung 1', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 48, 'unit_name' => 'PLTA T.Agung 2', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 49, 'unit_name' => 'PLTA Wlingi 1', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 50, 'unit_name' => 'PLTA Wlingi 2', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 51, 'unit_name' => 'PLTA Wonorejo', 'status' => 0, 'plant_id' => 13, 'tab_manual_aktif' => 3],
            ['unit_id' => 52, 'unit_name' => 'PLTA Cirata 1', 'status' => 0, 'plant_id' => 11, 'tab_manual_aktif' => 3],
            ['unit_id' => 53, 'unit_name' => 'PLTA Cirata 2', 'status' => 0, 'plant_id' => 11, 'tab_manual_aktif' => 3],
            ['unit_id' => 54, 'unit_name' => 'PLTA Cirata 3', 'status' => 0, 'plant_id' => 11, 'tab_manual_aktif' => 3],
            ['unit_id' => 55, 'unit_name' => 'PLTA Cirata 4', 'status' => 0, 'plant_id' => 11, 'tab_manual_aktif' => 3],
            ['unit_id' => 56, 'unit_name' => 'PLTA Cirata 5', 'status' => 0, 'plant_id' => 11, 'tab_manual_aktif' => 3],
            ['unit_id' => 57, 'unit_name' => 'PLTA Cirata 6', 'status' => 0, 'plant_id' => 11, 'tab_manual_aktif' => 3],
            ['unit_id' => 58, 'unit_name' => 'PLTA Cirata 7', 'status' => 0, 'plant_id' => 11, 'tab_manual_aktif' => 3],
            ['unit_id' => 59, 'unit_name' => 'PLTA Cirata 8', 'status' => 0, 'plant_id' => 11, 'tab_manual_aktif' => 3],
            ['unit_id' => 60, 'unit_name' => 'PLTGU Muara Tawar GT 1.1', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 61, 'unit_name' => 'PLTGU Muara Tawar GT 1.2', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 62, 'unit_name' => 'PLTGU Muara Tawar GT 1.3', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 63, 'unit_name' => 'PLTGU Muara Tawar GT 2.1', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 64, 'unit_name' => 'PLTGU Muara Tawar GT 2.2', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 65, 'unit_name' => 'PLTGU Muara Tawar GT 3.1', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 66, 'unit_name' => 'PLTGU Muara Tawar GT 3.2', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 67, 'unit_name' => 'PLTGU Muara Tawar GT 3.3', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 68, 'unit_name' => 'PLTGU Muara Tawar GT 4.1', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 69, 'unit_name' => 'PLTGU Muara Tawar GT 4.2', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 70, 'unit_name' => 'PLTGU Muara Tawar GT 4.3', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 71, 'unit_name' => 'PLTGU Muara Tawar GT 5.1', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 72, 'unit_name' => 'PLTGU Muara Tawar ST 1.0', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 73, 'unit_name' => 'PLTGU Muara Tawar ST 5.8', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 74, 'unit_name' => 'PLTGU Muara Karang GT 1.1', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 75, 'unit_name' => 'PLTGU Muara Karang GT 1.2', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 76, 'unit_name' => 'PLTGU Muara Karang GT 1.3', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 77, 'unit_name' => 'PLTGU Muara Karang GT 2.1', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 78, 'unit_name' => 'PLTGU Muara Karang GT 2.2', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 79, 'unit_name' => 'PLTGU Muara Karang ST 1.0', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 80, 'unit_name' => 'PLTGU Muara Karang ST 2.01', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 81, 'unit_name' => 'PLTGU Muara Karang ST 2.02', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 82, 'unit_name' => 'PLTGU Muara Karang ST 2.03', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 83, 'unit_name' => 'PLTU MKrg U4', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 84, 'unit_name' => 'PLTU MKrg U5', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 85, 'unit_name' => 'PLTU Indramayu 1', 'status' => 0, 'plant_id' => 3, 'tab_manual_aktif' => 3],
            ['unit_id' => 86, 'unit_name' => 'PLTU Indramayu 2', 'status' => 0, 'plant_id' => 3, 'tab_manual_aktif' => 3],
            ['unit_id' => 87, 'unit_name' => 'PLTU Indramayu 3', 'status' => 0, 'plant_id' => 3, 'tab_manual_aktif' => 3],
            ['unit_id' => 88, 'unit_name' => 'PLTU Pacitan 1', 'status' => 0, 'plant_id' => 4, 'tab_manual_aktif' => 3],
            ['unit_id' => 89, 'unit_name' => 'PLTU Pacitan 2', 'status' => 0, 'plant_id' => 4, 'tab_manual_aktif' => 3],
            ['unit_id' => 90, 'unit_name' => 'PLTU Paiton 9', 'status' => 0, 'plant_id' => 2, 'tab_manual_aktif' => 3],
            ['unit_id' => 91, 'unit_name' => 'PLTU Tanjung Awar-Awar 1', 'status' => 0, 'plant_id' => 6, 'tab_manual_aktif' => 3],
            ['unit_id' => 92, 'unit_name' => 'PLTU Tanjung Awar-Awar 2', 'status' => 0, 'plant_id' => 6, 'tab_manual_aktif' => 3],
            ['unit_id' => 93, 'unit_name' => 'PLTU Rembang 1 (PLTU 20)', 'status' => 0, 'plant_id' => 7, 'tab_manual_aktif' => 3],
            ['unit_id' => 94, 'unit_name' => 'PLTU Rembang 2 (PLTU 10)', 'status' => 0, 'plant_id' => 7, 'tab_manual_aktif' => 3],
            ['unit_id' => 95, 'unit_name' => 'PLTU S2P Cilacap 1', 'status' => 0, 'plant_id' => 24, 'tab_manual_aktif' => 3],
            ['unit_id' => 96, 'unit_name' => 'PLTU S2P Cilacap 2', 'status' => 0, 'plant_id' => 24, 'tab_manual_aktif' => 3],
            ['unit_id' => 97, 'unit_name' => 'PLTU S2P Cilacap 3', 'status' => 0, 'plant_id' => 24, 'tab_manual_aktif' => 3],
            ['unit_id' => 98, 'unit_name' => 'PLTU S2P Cilacap 4', 'status' => 0, 'plant_id' => 24, 'tab_manual_aktif' => 3],
            ['unit_id' => 99, 'unit_name' => 'PLTU Jawa 7 1', 'status' => 0, 'plant_id' => 27, 'tab_manual_aktif' => 3],
            ['unit_id' => 100, 'unit_name' => 'PLTU Jawa 7 2', 'status' => 0, 'plant_id' => 27, 'tab_manual_aktif' => 3],
            ['unit_id' => 101, 'unit_name' => 'PLTU Tenayan 1', 'status' => 0, 'plant_id' => 8, 'tab_manual_aktif' => 3],
            ['unit_id' => 102, 'unit_name' => 'PLTU Tenayan 2', 'status' => 0, 'plant_id' => 8, 'tab_manual_aktif' => 3],
            ['unit_id' => 103, 'unit_name' => 'PLTMG Arun E. A1.1', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 104, 'unit_name' => 'PLTMG Arun E. A1.2', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 105, 'unit_name' => 'PLTMG Arun E. A1.3', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 106, 'unit_name' => 'PLTMG Arun E. A1.4', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 107, 'unit_name' => 'PLTMG Arun E. A2.6', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 108, 'unit_name' => 'PLTMG Arun E. A2.7', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 109, 'unit_name' => 'PLTMG Arun E. A2.8', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 110, 'unit_name' => 'PLTMG Arun E. A2.9', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 111, 'unit_name' => 'PLTMG Arun E. A2.10', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 112, 'unit_name' => 'PLTMG Arun E. A3.11', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 113, 'unit_name' => 'PLTMG Arun E. A3.12', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 114, 'unit_name' => 'PLTMG Arun E. A3.13', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 115, 'unit_name' => 'PLTMG Arun E. A3.14', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 116, 'unit_name' => 'PLTMG Arun E. A3.15', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 117, 'unit_name' => 'PLTMG Arun E. A4.16', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 118, 'unit_name' => 'PLTMG Arun E. A4.17', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 119, 'unit_name' => 'PLTMG Arun E. A4.18', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 120, 'unit_name' => 'PLTMG Arun E. A4.19', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 121, 'unit_name' => 'PLTG Duri 1', 'status' => 0, 'plant_id' => 19, 'tab_manual_aktif' => 3],
            ['unit_id' => 122, 'unit_name' => 'PLTU Belitung 1', 'status' => 0, 'plant_id' => 30, 'tab_manual_aktif' => 3],
            ['unit_id' => 123, 'unit_name' => 'PLTU Belitung 2', 'status' => 0, 'plant_id' => 30, 'tab_manual_aktif' => 3],
            ['unit_id' => 124, 'unit_name' => 'PLTU Bangka 1', 'status' => 0, 'plant_id' => 31, 'tab_manual_aktif' => 3],
            ['unit_id' => 125, 'unit_name' => 'PLTU Bangka 2', 'status' => 0, 'plant_id' => 31, 'tab_manual_aktif' => 3],
            ['unit_id' => 126, 'unit_name' => 'PLTU Banjarsari 1', 'status' => 0, 'plant_id' => 32, 'tab_manual_aktif' => 3],
            ['unit_id' => 127, 'unit_name' => 'PLTU Banjarsari 2', 'status' => 0, 'plant_id' => 32, 'tab_manual_aktif' => 3],
            ['unit_id' => 128, 'unit_name' => 'PLTA Asahan 1.1', 'status' => 0, 'plant_id' => 16, 'tab_manual_aktif' => 3],
            ['unit_id' => 129, 'unit_name' => 'PLTA Asahan 1.2', 'status' => 0, 'plant_id' => 16, 'tab_manual_aktif' => 3],
            ['unit_id' => 130, 'unit_name' => 'PLTA Batang Toru 1', 'status' => 0, 'plant_id' => 17, 'tab_manual_aktif' => 3],
            ['unit_id' => 131, 'unit_name' => 'PLTA Batang Toru 2', 'status' => 0, 'plant_id' => 17, 'tab_manual_aktif' => 3],
            ['unit_id' => 132, 'unit_name' => 'PLTA Batang Toru 3', 'status' => 0, 'plant_id' => 17, 'tab_manual_aktif' => 3],
            ['unit_id' => 133, 'unit_name' => 'PLTA Batang Toru 4', 'status' => 0, 'plant_id' => 17, 'tab_manual_aktif' => 3],
            ['unit_id' => 134, 'unit_name' => 'PLTU Kaltim Teluk 1', 'status' => 0, 'plant_id' => 9, 'tab_manual_aktif' => 3],
            ['unit_id' => 135, 'unit_name' => 'PLTU Kaltim Teluk 2', 'status' => 0, 'plant_id' => 9, 'tab_manual_aktif' => 3],
            ['unit_id' => 136, 'unit_name' => 'PLTU Pulang Pisau 1', 'status' => 0, 'plant_id' => 10, 'tab_manual_aktif' => 3],
            ['unit_id' => 137, 'unit_name' => 'PLTU Pulang Pisau 2', 'status' => 0, 'plant_id' => 10, 'tab_manual_aktif' => 3],
            ['unit_id' => 138, 'unit_name' => 'PLTU Ketapang 1', 'status' => 0, 'plant_id' => 26, 'tab_manual_aktif' => 3],
            ['unit_id' => 139, 'unit_name' => 'PLTU Ketapang 2', 'status' => 0, 'plant_id' => 26, 'tab_manual_aktif' => 3],
            ['unit_id' => 140, 'unit_name' => 'PLTU Tembilahan 1', 'status' => 0, 'plant_id' => 22, 'tab_manual_aktif' => 3],
            ['unit_id' => 141, 'unit_name' => 'PLTU Tembilahan 2', 'status' => 0, 'plant_id' => 22, 'tab_manual_aktif' => 3],
            ['unit_id' => 142, 'unit_name' => 'PLTD Suppa 1', 'status' => 0, 'plant_id' => 18, 'tab_manual_aktif' => 3],
            ['unit_id' => 143, 'unit_name' => 'PLTD Suppa 2', 'status' => 0, 'plant_id' => 18, 'tab_manual_aktif' => 3],
            ['unit_id' => 144, 'unit_name' => 'PLTD Suppa 3', 'status' => 0, 'plant_id' => 18, 'tab_manual_aktif' => 3],
            ['unit_id' => 145, 'unit_name' => 'PLTD Suppa 4', 'status' => 0, 'plant_id' => 18, 'tab_manual_aktif' => 3],
            ['unit_id' => 146, 'unit_name' => 'PLTD Suppa 5', 'status' => 0, 'plant_id' => 18, 'tab_manual_aktif' => 3],
            ['unit_id' => 147, 'unit_name' => 'PLTD Suppa 6', 'status' => 0, 'plant_id' => 18, 'tab_manual_aktif' => 3],
            ['unit_id' => 148, 'unit_name' => 'PLTU Ampana 1', 'status' => 0, 'plant_id' => 20, 'tab_manual_aktif' => 3],
            ['unit_id' => 149, 'unit_name' => 'PLTU Ampana 2', 'status' => 0, 'plant_id' => 20, 'tab_manual_aktif' => 3],
            ['unit_id' => 150, 'unit_name' => 'PLTU Amurang 1', 'status' => 0, 'plant_id' => 21, 'tab_manual_aktif' => 3],
            ['unit_id' => 151, 'unit_name' => 'PLTU Amurang 2', 'status' => 0, 'plant_id' => 21, 'tab_manual_aktif' => 3],
            ['unit_id' => 152, 'unit_name' => 'PLTU Talaud 1', 'status' => 0, 'plant_id' => 23, 'tab_manual_aktif' => 3],
            ['unit_id' => 153, 'unit_name' => 'PLTU Talaud 2', 'status' => 0, 'plant_id' => 23, 'tab_manual_aktif' => 3],
            ['unit_id' => 154, 'unit_name' => 'PLTU Kendari 1', 'status' => 0, 'plant_id' => 28, 'tab_manual_aktif' => 3],
            ['unit_id' => 155, 'unit_name' => 'PLTU Kendari 2', 'status' => 0, 'plant_id' => 28, 'tab_manual_aktif' => 3],
            ['unit_id' => 156, 'unit_name' => 'PLTU Anggrek 1', 'status' => 0, 'plant_id' => 33, 'tab_manual_aktif' => 3],
            ['unit_id' => 157, 'unit_name' => 'PLTU Anggrek 2', 'status' => 0, 'plant_id' => 33, 'tab_manual_aktif' => 3],
            ['unit_id' => 158, 'unit_name' => 'PLTU Ropa 1', 'status' => 0, 'plant_id' => 25, 'tab_manual_aktif' => 3],
            ['unit_id' => 159, 'unit_name' => 'PLTU Ropa 2', 'status' => 0, 'plant_id' => 25, 'tab_manual_aktif' => 3],
            ['unit_id' => 160, 'unit_name' => 'PLTU Bolok 1', 'status' => 0, 'plant_id' => 29, 'tab_manual_aktif' => 3],
            ['unit_id' => 161, 'unit_name' => 'PLTU Bolok 2', 'status' => 0, 'plant_id' => 29, 'tab_manual_aktif' => 3],
            ['unit_id' => 162, 'unit_name' => 'PLTU Tidore 1', 'status' => 0, 'plant_id' => 15, 'tab_manual_aktif' => 3],
            ['unit_id' => 163, 'unit_name' => 'PLTU Tidore 2', 'status' => 0, 'plant_id' => 15, 'tab_manual_aktif' => 3],
            ['unit_id' => 164, 'unit_name' => 'PLTGU Gresik Blok 1', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 165, 'unit_name' => 'PLTGU Gresik Blok 2', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 166, 'unit_name' => 'PLTGU Gresik Blok 3', 'status' => 0, 'plant_id' => 36, 'tab_manual_aktif' => 3],
            ['unit_id' => 167, 'unit_name' => 'PLTGU Muara Tawar Blok 1', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 168, 'unit_name' => 'PLTGU Muara Tawar Blok 2', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 169, 'unit_name' => 'PLTGU Muara Tawar Blok 3', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 170, 'unit_name' => 'PLTGU Muara Tawar Blok 4', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 171, 'unit_name' => 'PLTGU Muara Tawar Blok 5', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 172, 'unit_name' => 'PLTGU Muara Karang Blok 1', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 173, 'unit_name' => 'PLTGU Muara Karang Blok 2', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 174, 'unit_name' => 'PLTGU Muara Karang Blok 3', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 175, 'unit_name' => 'PLTU Muarakarang 4', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 176, 'unit_name' => 'PLTU Muarakarang 5', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 178, 'unit_name' => 'PLTMG Arun E. A1.5', 'status' => 0, 'plant_id' => 12, 'tab_manual_aktif' => 3],
            ['unit_id' => 179, 'unit_name' => 'PLTU Tarahan 3', 'status' => 0, 'plant_id' => 37, 'tab_manual_aktif' => 3],
            ['unit_id' => 180, 'unit_name' => 'PLTU Tarahan 4', 'status' => 0, 'plant_id' => 37, 'tab_manual_aktif' => 3],
            ['unit_id' => 181, 'unit_name' => 'PLTGU Belawan Blok 1', 'status' => 0, 'plant_id' => 38, 'tab_manual_aktif' => 3],
            ['unit_id' => 182, 'unit_name' => 'PLTGU Belawan Blok 2', 'status' => 0, 'plant_id' => 38, 'tab_manual_aktif' => 3],
            ['unit_id' => 183, 'unit_name' => 'PLTA Besai 1', 'status' => 0, 'plant_id' => 39, 'tab_manual_aktif' => 3],
            ['unit_id' => 184, 'unit_name' => 'PLTA Besai 2', 'status' => 0, 'plant_id' => 39, 'tab_manual_aktif' => 3],
            ['unit_id' => 185, 'unit_name' => 'PLTA Batutegi 1', 'status' => 0, 'plant_id' => 39, 'tab_manual_aktif' => 3],
            ['unit_id' => 186, 'unit_name' => 'PLTA Batutegi 2', 'status' => 0, 'plant_id' => 39, 'tab_manual_aktif' => 3],
            ['unit_id' => 187, 'unit_name' => 'PLTA Bakaru 1', 'status' => 0, 'plant_id' => 40, 'tab_manual_aktif' => 3],
            ['unit_id' => 188, 'unit_name' => 'PLTA Bakaru 2', 'status' => 0, 'plant_id' => 40, 'tab_manual_aktif' => 3],
            ['unit_id' => 189, 'unit_name' => 'PLTA Sawitto 1', 'status' => 0, 'plant_id' => 40, 'tab_manual_aktif' => 3],
            ['unit_id' => 190, 'unit_name' => 'PLTA Sawitto 2', 'status' => 0, 'plant_id' => 40, 'tab_manual_aktif' => 3],
            ['unit_id' => 191, 'unit_name' => 'PLTA Sawitto 3', 'status' => 0, 'plant_id' => 40, 'tab_manual_aktif' => 3],
            ['unit_id' => 192, 'unit_name' => 'PLTGU Belawan GT11', 'status' => 0, 'plant_id' => 38, 'tab_manual_aktif' => 3],
            ['unit_id' => 193, 'unit_name' => 'PLTGU Belawan GT12', 'status' => 0, 'plant_id' => 38, 'tab_manual_aktif' => 3],
            ['unit_id' => 194, 'unit_name' => 'PLTGU Belawan ST10', 'status' => 0, 'plant_id' => 38, 'tab_manual_aktif' => 3],
            ['unit_id' => 195, 'unit_name' => 'PLTGU Belawan GT21', 'status' => 0, 'plant_id' => 38, 'tab_manual_aktif' => 3],
            ['unit_id' => 196, 'unit_name' => 'PLTGU Belawan GT22', 'status' => 0, 'plant_id' => 38, 'tab_manual_aktif' => 3],
            ['unit_id' => 197, 'unit_name' => 'PLTGU Belawan ST20', 'status' => 0, 'plant_id' => 38, 'tab_manual_aktif' => 3],
            ['unit_id' => 198, 'unit_name' => 'PLTU Sebalang 1', 'status' => 0, 'plant_id' => 41, 'tab_manual_aktif' => 3],
            ['unit_id' => 199, 'unit_name' => 'PLTU Sebalang 2', 'status' => 0, 'plant_id' => 41, 'tab_manual_aktif' => 3],
            ['unit_id' => 200, 'unit_name' => 'PLTU Punagaya 1', 'status' => 0, 'plant_id' => 42, 'tab_manual_aktif' => 3],
            ['unit_id' => 201, 'unit_name' => 'PLTU Punagaya 2', 'status' => 0, 'plant_id' => 42, 'tab_manual_aktif' => 3],
            ['unit_id' => 202, 'unit_name' => 'PLTGU Muara Tawar ST 1.4', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 203, 'unit_name' => 'PLTGU Muara Tawar ST 2.0', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 204, 'unit_name' => 'PLTGU Muara Tawar ST 3.0', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 205, 'unit_name' => 'PLTGU Muara Tawar ST 4.0', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 206, 'unit_name' => 'PLTGU Muara Tawar GT 5.1', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 207, 'unit_name' => 'PLTGU Muara Tawar ST 5.8', 'status' => 0, 'plant_id' => 34, 'tab_manual_aktif' => 3],
            ['unit_id' => 208, 'unit_name' => 'PLTA Sipansihaporas 1', 'status' => 0, 'plant_id' => 44, 'tab_manual_aktif' => 3],
            ['unit_id' => 209, 'unit_name' => 'PLTA Sipansihaporas 2', 'status' => 0, 'plant_id' => 44, 'tab_manual_aktif' => 3],
            ['unit_id' => 210, 'unit_name' => 'PLTA Renun 1', 'status' => 0, 'plant_id' => 44, 'tab_manual_aktif' => 3],
            ['unit_id' => 211, 'unit_name' => 'PLTA Renun 2', 'status' => 0, 'plant_id' => 44, 'tab_manual_aktif' => 3],
            ['unit_id' => 212, 'unit_name' => 'PLTA Koto Panjang 1', 'status' => 0, 'plant_id' => 45, 'tab_manual_aktif' => 3],
            ['unit_id' => 213, 'unit_name' => 'PLTA Koto Panjang 2', 'status' => 0, 'plant_id' => 45, 'tab_manual_aktif' => 3],
            ['unit_id' => 214, 'unit_name' => 'PLTA Koto Panjang 3', 'status' => 0, 'plant_id' => 45, 'tab_manual_aktif' => 3],
            ['unit_id' => 215, 'unit_name' => 'PLTA Tanggari 1', 'status' => 0, 'plant_id' => 43, 'tab_manual_aktif' => 3],
            ['unit_id' => 216, 'unit_name' => 'PLTA Tanggari 2', 'status' => 0, 'plant_id' => 43, 'tab_manual_aktif' => 3],
            ['unit_id' => 217, 'unit_name' => 'PLTA Tanggari 3', 'status' => 0, 'plant_id' => 43, 'tab_manual_aktif' => 3],
            ['unit_id' => 218, 'unit_name' => 'PLTA Tanggari 4', 'status' => 0, 'plant_id' => 43, 'tab_manual_aktif' => 3],
            ['unit_id' => 219, 'unit_name' => 'PLTU Nagan Raya 1', 'status' => 0, 'plant_id' => 46, 'tab_manual_aktif' => 3],
            ['unit_id' => 220, 'unit_name' => 'PLTU Nagan Raya 2', 'status' => 0, 'plant_id' => 46, 'tab_manual_aktif' => 3],
            ['unit_id' => 221, 'unit_name' => 'PLTGU Sengkang GT11', 'status' => 0, 'plant_id' => 47, 'tab_manual_aktif' => 3],
            ['unit_id' => 222, 'unit_name' => 'PLTGU Sengkang GT12', 'status' => 0, 'plant_id' => 47, 'tab_manual_aktif' => 3],
            ['unit_id' => 223, 'unit_name' => 'PLTGU Sengkang ST18', 'status' => 0, 'plant_id' => 47, 'tab_manual_aktif' => 3],
            ['unit_id' => 224, 'unit_name' => 'PLTGU Sengkang GT21', 'status' => 0, 'plant_id' => 47, 'tab_manual_aktif' => 3],
            ['unit_id' => 225, 'unit_name' => 'PLTGU Sengkang GT22', 'status' => 0, 'plant_id' => 47, 'tab_manual_aktif' => 3],
            ['unit_id' => 226, 'unit_name' => 'PLTGU Sengkang ST28', 'status' => 0, 'plant_id' => 47, 'tab_manual_aktif' => 3],
            ['unit_id' => 227, 'unit_name' => 'PLTGU Muara Karang GT 3.1', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 228, 'unit_name' => 'PLTGU Muara Karang ST 3.0', 'status' => 0, 'plant_id' => 35, 'tab_manual_aktif' => 3],
            ['unit_id' => 229, 'unit_name' => 'PLTMG BauBau 1', 'status' => 0, 'plant_id' => 48, 'tab_manual_aktif' => 3],
            ['unit_id' => 231, 'unit_name' => 'PLTMG BauBau 2', 'status' => 0, 'plant_id' => 48, 'tab_manual_aktif' => 3],
            ['unit_id' => 232, 'unit_name' => 'PLTMG BauBau 3', 'status' => 0, 'plant_id' => 48, 'tab_manual_aktif' => 3],
            ['unit_id' => 233, 'unit_name' => 'PLTMG BauBau 4', 'status' => 0, 'plant_id' => 48, 'tab_manual_aktif' => 3],
            ['unit_id' => 234, 'unit_name' => 'PLTMG Bima 1', 'status' => 0, 'plant_id' => 49, 'tab_manual_aktif' => 3],
            ['unit_id' => 235, 'unit_name' => 'PLTMG Bima 2', 'status' => 0, 'plant_id' => 49, 'tab_manual_aktif' => 3],
            ['unit_id' => 236, 'unit_name' => 'PLTMG Bima 3', 'status' => 0, 'plant_id' => 49, 'tab_manual_aktif' => 3],
            ['unit_id' => 237, 'unit_name' => 'PLTMG Kendari 1', 'status' => 0, 'plant_id' => 50, 'tab_manual_aktif' => 3],
            ['unit_id' => 238, 'unit_name' => 'PLTMG Kendari 2', 'status' => 0, 'plant_id' => 50, 'tab_manual_aktif' => 3],
            ['unit_id' => 239, 'unit_name' => 'PLTMG Kendari 3', 'status' => 0, 'plant_id' => 50, 'tab_manual_aktif' => 3],
            ['unit_id' => 240, 'unit_name' => 'PLTMG Kendari 4', 'status' => 0, 'plant_id' => 50, 'tab_manual_aktif' => 3],
            ['unit_id' => 241, 'unit_name' => 'PLTMG Kendari 5', 'status' => 0, 'plant_id' => 50, 'tab_manual_aktif' => 3],
            ['unit_id' => 242, 'unit_name' => 'PLTMG Kendari 6', 'status' => 0, 'plant_id' => 50, 'tab_manual_aktif' => 3],
            ['unit_id' => 243, 'unit_name' => 'PLTGU Sengkang Blok 1', 'status' => 0, 'plant_id' => 47, 'tab_manual_aktif' => 3],
            ['unit_id' => 244, 'unit_name' => 'PLTGU Sengkang Blok 2', 'status' => 0, 'plant_id' => 47, 'tab_manual_aktif' => 3],
        ]);
    }
}
