services:
  # Laravel Application with built assets
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: performance-testing-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./.env:/app/.env
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=50M
      - PHP_UPLOAD_MAX_FILESIZE=50M
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: bridge
